### ISSUE TITLE
Key generation failed: File exists

### ISSUE THREAD

**Issue by phuongnd08** [LedgerHQ/app-openpgp#109]
I use `gpg --card-edit` to generate a seeded key on the device. Every time I'm getting this after filling all the information:

```
Key generation failed: File exists
```

Which file is that?

**Comment by cedelavergne-ledger** [comment]
Hi,
This is a gpg error, I cannot have more details.
Did you try using the verbose mode?
Also, I don't know if you already have some keys / configurations, but for my tests, using a tmp folder, I always delete the gnupg folder to ensure there is no pibring or private keys..

**Comment by phuongnd08** [comment]
Right, I delete the whole gpg folder to hard reset and can generate again, thanks.
