### ISSUE TITLE
Is there a clear documentation?

### ISSUE THREAD

**Issue by FabrizioRomanoGenovese** [LedgerHQ/app-openpgp#26]
I have given a look to:
https://github.com/LedgerHQ/blue-app-openpgp-card/blob/master/doc/user/blue-app-openpgp-card.pdf

But it is a rather difficult file to follow. I'd like to know if the following is possible:

- Generate a GPG key on the device using its seed words (it seems that this is possible, albeit the feature is marked as experimental). This would allow me to recover the keys from the seed in case my nano is lost or broken;
- Use this GPG key to sign subkeys;
- Keep the subkeys on my PC so that, for instance, I can sign my github commits with them without having to plug in my nano all the time.

In the use case above the nano is only used to generate a master key with which other keys can be signed, and this master key is recoverable from the seed words. There is, to my knowledge, no clear explanation about how to achieve this. I am quite sure that such use case would be common among other people as well, so it would be very nice if it could be documented in detail. I am more than willing to help with this, but I need to understand how the process works and if it's doable before drafting a guide.

**Comment by sg495** [comment]
I concur: seed mode key generation is undoubtedly one of the most interesting features of this app. It would be good to have the technical details from [doc/developper/gpgcard3.0-addon.rst](https://github.com/LedgerHQ/blue-app-openpgp-card/blob/master/doc/developper/gpgcard3.0-addon.rst) clearly integrated into the main documentation, and the whole key generation experience made a little less "experimental" (e.g. see issue #29).

**Comment by gaellalire** [comment]
I made a documentation for my usecase (seed mode, only for primary key)
https://github.com/gaellalire/ledgerwallet/blob/master/README.md

**Comment by guillaumedc** [comment]
The versionized PDF seams broken.

There is a `generate.sh` script but it's hard to make it work, since there is no documentation on how to use it, or even which are the dependencies to build the doc...

**Comment by pjz** [comment]
I don't know where to document the doc-generation dependencies, but they seem to be met by doing (on my Ubuntu 18.04 system):
```
apt install pandoc texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
```

**Comment by cedelavergne-ledger** [comment]
Hi,
App has been refactored in v2.0.0 and the doc a little bit reviewed.
Can you please check again, in `develop` branch, and tell me what is still missing or unclear?
