### ISSUE TITLE
ledger nano x compatibility

### ISSUE THREAD

**Issue by mhhf** [LedgerHQ/app-openpgp#46]
I'm a heavy user of this app with my nano s and was wondering if and when it will appear for my ledger x.

**Comment by fubuloubu** [comment]
This was actually the main reason I bought the X, what's involved in getting the X to be compatible?

**Comment by cslashm** [comment]
I had to port the UI. I was just a bit buzy this last days, sorry . But I'm on the deck and will work on very very soon.
I also use it every day and need it :p

**Comment by jonathancross** [comment]
@cslashm Any updates for us here?

**Comment by aitorpazos** [comment]
I was testing this on my ledger nano x and it reboots when asked to generate the keys (Using https://salsa.debian.org/rousseau/CCID from master as it contains the addition to support it in libccid)

**Comment by aitorpazos** [comment]
Further testing resulted in ECC Curve 25519 keys being generated correctly :) . I suspect the issue may be related to the fact that I was using RSA 4096 in my first tests and the key sizes may become too big for the app (RSA 2048 worked fine as well).

**Comment by cslashm** [comment]
I think the time to generated 4096 is too long and the host ccid trigger a timeout

**Comment by jonathancross** [comment]
@cslashm  Are you still working on Nano X support or should it be considered complete (at least for `Curve25519`)?

**Comment by cslashm** [comment]
The deployed version is the one I use day to day. (and with cv/ed-25519))
Dont forget to backup/resetore with provided  pythontool.

**Comment by jonathancross** [comment]
Thanks for the reply.
> backup/resetore with provided pythontool.

So the seed backup isn't enough to restore pgp keys?

**Comment by cslashm** [comment]
@jonathancross yes it is
