### ISSUE TITLE
Typos in gpgcli.py for Edward curve 25519

### ISSUE THREAD

**Issue by Pantamis** [LedgerHQ/app-openpgp#52]
I tested the ed25519 key recovery with seed mode.

It seems to work most of the time, but for template I had to input "ed255519" instead of "ed25519" (one more "5"). It is a typo in the template's dictionnary definition in gpgcli.py.

I also noticed a missing "1" in the epilog of the argparser in the same file ("ed2559" instead of "ed25519").

Thank you for this app that I find very underated (fully compliant OpenPGP smartcard with possibility of an BIP32-like backup with seed mode :+1: , I have choosen Ledger just for this !)

**Comment by cslashm** [comment]
Thanks for reporting that.

**Comment by cedelavergne-ledger** [comment]
Hi,
Seems it is fixed now in App v2.0.0 (still in develop `branch`).
Can you please double check?
