### ISSUE TITLE
PDF documentation linked in support page is corrupted

### ISSUE THREAD

**Issue by ghost** [LedgerHQ/app-openpgp#55]
Hi.

I arrived here following the link in from there: https://support.ledger.com/hc/en-us/articles/115005200649-OpenPGP, and the linked to PDF documentation at https://github.com/LedgerHQ/openpgp-card-app/blob/master/doc/user/blue-app-openpgp-card.pdf is invalid :/. The previous version of this file in the history seems corrupted as well.

**Comment by ReneHonig** [comment]
I had the same problem. The file is corrupted in a number of programs but I can open it in Chrome and Edge.

**Comment by wigy-opensource-developer** [comment]
```sh
$ file blue-app-openpgp-card.pdf 
blue-app-openpgp-card.pdf: PDF document, version 1.5
```
Chromium 83.0.4103.61 on Linux opens them fine, so it could be an extension or bug in the PDF writer software?

**Comment by omarabid** [comment]
Same problem here in Mac/Archlinux. Chrome opens the PDF file but it's blank.

**Comment by N1c3** [comment]
same macos with chrome wont open the file

**Comment by riordant** [comment]
Same issue here with MacoS. Catalina issue?

**Comment by guiand88** [comment]
Bumping this up.
File appears corrupted under Arch and Chromium/LibreWolf.
It also appears corrupted when downloaded from those same browser and opened with Okular.

**Comment by wigy-opensource-developer** [comment]
@cslashm Sorry to mention you, but maybe this issue was buried in your inbox?

**Comment by wigy-opensource-developer** [comment]
Seems like #56 fixed this issue? The following PDF is now readable in Firefox/Linux and Atril Document Viewer/Linux:

https://github.com/LedgerHQ/openpgp-card-app/blob/master/doc/user/blue-app-openpgp-card.pdf

**Comment by lgillot-lamure-ledger** [comment]
Yes :+1:

**Comment by cedelavergne-ledger** [comment]
Hi,
The repository has been updated, and the app refactored.
Please check again the doc pdf.
Please just note the links to the pdf in the different makdown files are targetting the `master` branch, whereas for the moment, the App is still under test and review (not yet merged in `master`, still in `develop`). Meaning the direct links are not yet fully fixed, but the pdf documents are available from the `doc/ `directory.
