### ISSUE TITLE
Seeded mode: support "strict" mode which hard-codes all other key data for deterministic fingerprints

### ISSUE THREAD

**Issue by colemickens** [LedgerHQ/app-openpgp#67]
If I understand correctly, there's currently an "issue", in that the "seeded" mode can generate reproducible, deterministic private/public keys for openpgp, but that the fingerprints contain other data (some of which is easily user-controller, some of which isn't).

I am hoping to leverage the Ledger as single point of reference in the case of my demise. I can leverage SSKR to distribute my my master key, and then leave instructions for using the SSKR-recovered Ledger with the OpenPGP app to decrypt my text file containing my bank accounts, extra tokens, special instructions for beneficiaries, etc.

This is a bit impractical today, due to this application: (1) not defaulting to seeded mode (easy enough to document), and (2) the differing fingerprints making GPG a real pain to work with.

**Comment by colemickens** [comment]
It appears that there might be better options for me, already:
1. `app-passwords` could be used along with pre-established secret names
2. `app-sshagent` looks to maybe be better supported via the `trezor-agent` ecosystem (which, despite the name, supports ledger devices).

Particularly, the first option would be fine for non-GPG use cases, and the second options is useful for GPG/SSH cases **and it already supports restoring from a specific timestamp and documents how to extract the correct timestamp from an existing pubkey**.

**Comment by colemickens** [comment]
Maybe this is a documentation thing as well? Is there a way to instruct `gpg` on how to generate the keys all in one-go (including the author, email, and timestamp)?

**Comment by colemickens** [comment]
Okay, so gpg has `--fakes-system-time` but it sets the time from the application start, so the amount of time you take entering information affects what is generated.

gpg is truly something to behold.

**Comment by colemickens** [comment]
aha!  from the gpg docs: `If you suffix epoch with an exclamation mark (!), the system time will appear to be frozen at the specified time.`

So here's the procedure:

1. Reset the Ledger OpenPGP.XL app
2. Ensure you set "seeded" mode to true.
2. Set the key template to ed25519 for each of the key types.
3. Wipe your OpenGPG working data (this is to keep openpgp from getting confused due to it's attempt to cache card ids/pubkeys/fingerprints)
4. Use `gpg --faked-system-time 19990101T000000! --card-edit` (note the exclamation mark, and the user-chosen timestamp).

You need to use the same exact name and email, as well.

I have repeated this process now multiple times. I have gotten unique "serial number"s with the exact same fingerprints, etc.

**Comment by colemickens** [comment]
Opened a PR for the readme to document this: https://github.com/LedgerHQ/openpgp-card-app/pull/68

**Comment by colemickens** [comment]
Now that I'm trying again, I'm getting different results after resetting the application on the Ledger.

**Comment by colemickens** [comment]
Thats because I forgot seeded mode...

**Comment by cedelavergne-ledger** [comment]
This is now a closed issue, rigth? 
Please check also v2, containing lots of refactoring.
