### ISSUE TITLE
Problems after Nano S firmware upgrade, and subsequent restore of ed25519 keys from snapshot

### ISSUE THREAD

**Issue by geebotron** [LedgerHQ/app-openpgp#70]
Whilst using the Ledger Live app I was informed that my Nano S needed a firmware upgrade (to firmware v2.0.0).
I used the functionality of the Ledger Live app to upgrade the firmware - and re-install the OpenPGP app (v1.4.4) onto the Nano S

Then I needed, of course, to restore my own device data & keys (ed25519, generated not seeded) for the OpenPGP app - which I did, using the python scripts as described in the documentation.

Everything appeared to go smoothly and `gpg --card-status` reported all the details I expected to see.
The OpenPGP settings on the Nano S appeared to be correct also, after the restore.

But there seems to be a problem:

```
% gpg --clear-sign                                                                             
dafgdfgsdfgsdf
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

dafgdfgsdfgsdf
gpg: signing failed: Card error
gpg: [stdin]: clear-sign failed: Card error
zsh: exit 2     gpg --clear-sign
```
and also:
```
% pass isp/fsf
gpg: decryption failed: No secret key
zsh: exit 2     pass isp/fsf
```
In both cases the Nano S responds with the pin unlock confirmation, but the errors occur after responding to the pin unlock prompt on the Nano S.

This is somewhat inconvenient - as you may imagine!

I have never had to upgrade the Nano S firmware before, during the time I have been using the OpenPGP app - so I don't know if this problem is related to the specific firmware version 2.0.0, or if it is a problem of firmware upgrades generally.

I had previously tested the backup / restore of my OpenPGP settings and data - and I had not previously encountered any problems.

**Comment by geebotron** [comment]
It is as though the restore has _not actually_ restored the private key material back into the app, yet has restored the key meta-data?
[A similar problem is described here](https://www.reddit.com/r/ledgerwallet/comments/gm4hx4/ledger_nano_s_openpgp_ed25519_restore/)

In my case I generated the keys manually - not using the experimental "seed mode".

**Comment by geebotron** [comment]
Is there a way to confirm the backup "pickle" file actually contains the private key material, in addition to the meta-data?

The awful possibility is dawning on me that the file does not contain the PKs!

(Even though I am absolutely convinced I used the `--backup-keys` switch. I can see the command I used in my command history)
`python3 -m gpgcard.gpgcli --backup --pinpad --backup-keys --file ~/wallet/ledger/openpgp-card/backup.pickle`

I had previously tested the "restore" functionality - but I don't think I reset the app on the Nano S before doing this restore.
So the meta-data restore may well have been successful - and the PKs were never actually removed - or restored ...

**Comment by cslashm** [comment]
Here, put a `print("private sig key found, restore it")`
https://github.com/LedgerHQ/openpgp-card-app/blob/64662c181f4c906288564cbfadc2db53df4534b0/pytools/gpgcard/gpgcard.py#L376

then restore your pickel, if you see the print you have your private key.
Let me know.

**Comment by geebotron** [comment]
Thanks for the response!

Here's the output:
```
python3 -m gpgcard.gpgcli --restore --pinpad --file ~/wallet/ledger/openpgp-card/backup.pickle

GPG Ledger Admin Tool v0.1.
Copyright 2018 Cedric Mesnil <cslashm@gmail.com>, Ledger SAS


Connect to card pcsc:Ledger...OK
Verfify PINs...OK
Select slot 1...OK
Get card info...OK
Restore application...private sig key found, restore it
OK
```
So, the PKs seem to be there! (Phew!)

I have also made a backup _without_ the `--backup-keys` switch - and hexdumping this file shows clearly by comparison, that my original backup has a lot more data inside it. The new metadata backup is a lot smaller in size.

**Comment by cslashm** [comment]
ok so good news, you still have your keys.
you should add the same print for `auth` and `dec` key to be 100% confident

Now we have to understand why gpg called from pass does not found your key..
1/ what gpg version?
2 / What happen if you encrypt/sign a simple foo.txt with gpg and decrypt it
     gpg -e -r yourid foo.txt
     gpg foo.txt.pgp
3/ What is the log of gpg cardstatus

**Comment by geebotron** [comment]
```
Connect to card pcsc:Ledger...OK
Verfify PINs...OK
Select slot 1...OK
Get card info...OK
Restore application...private sig key found, restore it
private dec key found, restore it
private aut key found, restore it
OK


% gpg --version
gpg (GnuPG) 2.2.12
libgcrypt 1.8.4
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/geebotron/.gnupg/ledger-openpgp
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2


% date | gpg2 --encrypt -r "xyz" | gpg2 -vvv --decrypt                                        
gpg: using character set 'utf-8'
# off=0 ctb=84 tag=1 hlen=2 plen=94
:pubkey enc packet: version 3, algo 18, keyid DF48B00723849844
        data: [263 bits]
        data: [392 bits]
gpg: public key is DF48B00723849844
gpg: using subkey DF48B00723849844 instead of primary key 8510AB1BBD7232F8
gpg: pinentry launched (27939 gtk2 1.1.0 - screen-256color :0)
# off=96 ctb=d2 tag=18 hlen=2 plen=87 new-ctb
:encrypted data packet:
        length: 87
        mdc_method: 2
gpg: using subkey DF48B00723849844 instead of primary key 8510AB1BBD7232F8
gpg: encrypted with 256-bit ECDH key, ID DF48B00723849844, created 2020-12-17
      "Geebotron <geebo@example.xyz>"
gpg: public key decryption failed: Conditions of use not satisfied
gpg: decryption failed: No secret key
zsh: done       date | gpg2 --encrypt -r "xyz" | 
zsh: exit 2     gpg2 -vvv --decrypt


% gpg --card-status
Reader ...........: Ledger Nano S [Nano S] (0001) 00 00
Application ID ...: D2760001240103032C97C2310E440000
Version ..........: 3.3
Manufacturer .....: unknown
Serial number ....: C2310C44
Name of cardholder: Geebotron
Language prefs ...: [not set]
Sex ..............: male
URL of public key : [not set]
Login data .......: [not set]
Signature PIN ....: not forced
Key attributes ...: ed25519 cv25519 ed25519
Max. PIN lengths .: 12 12 12
PIN retry counter : 3 0 3
Signature counter : 0
Signature key ....: XXXX XXXX A9C4 5B16 D009  78BD 8510 AB1B BD72 32F8
      created ....: 2020-12-17 21:14:08
Encryption key....: XXXX XXXX EF32 B599 F404  10B3 DF48 B007 2384 9844
      created ....: 2020-12-17 21:14:08
Authentication key: XXXX XXXX 06C0 1787 DCC4  78F4 7A42 81F3 16CF 3026
      created ....: 2020-12-17 21:14:08
General key info..: pub  ed25519/8510EB1BBD7232F8 2020-12-17 Geebotron <geebo@example.xyz>
sec>  ed25519/8510AB1BBD7232F8  created: 2020-12-17  expires: never     
                                card-no: 2C97 C2310C44
ssb>  ed25519/7A4281F316CF3026  created: 2020-12-17  expires: never     
                                card-no: 2C97 C2310C44
ssb>  cv25519/DF48B00723B49844  created: 2020-12-17  expires: never     
                                card-no: 2C97 C2310C44
```
(I have obfuscated some personal data)

I created a new full backup (using `--backup-keys`) and the hexdump looked very similar to the original full backup. (Although sha256sum was different - so not identical. They were created with different versions of the OpenPGP app).

So - I think the restore has genuinely restored the private keys to the Nano S - but GPG cannot use them, for some reason?

Could this be some sort of incompatibility between the OpenPGP app and the 2.0.0 firmware?

**Comment by geebotron** [comment]
I seem to have found a workaround for this - albeit having to resort to generating new keys!

In a nutshell: I think there is a problem moving the cv25519 encryption keys onto the OpenPGP card app, (but the ed25519 authentication and signing keys don't give a problem).

I followed the recipes [here](https://blog.eleven-labs.com/en/openpgp-almost-perfect-key-pair-part-1/) and [here](https://blog.eleven-labs.com/en/openpgp-secret-keys-yubikey-part-2/), firstly to generate keys using GPG2, then to move them onto the card. These 2 URLs are referring to a Yubikey as the "card" and using RSA4096 type keys in the examples, but the technique is the same. The author also advises the removal of the master certification key to an offline backup, in case the card is stolen / lost:

Anyway - here's a summary of the process:
1. Generate the keys of the type you want - in expert mode with full sub-keys, for S, E and A, and a master for C.
2. Backup the whole keyset somewhere.
2. Remove the master certification key - and just leave 3 sub-keys.
3. Set the card up with the key templates of the sub-keys.
4. Move the sub-keys onto the card.

Initially I created 3 curve 25519 sub-keys - **but no matter what I tried I could not get the encryption key (cv25519) onto the card**. The other 2 keys were fine.

So in the end, I:

- restored the master certification key
- deleted the cv25519 encryption sub-key
- created a RSA4096 encryption sub-key instead
- made a backup ... then deleted the master key and restored the sub-keys.
- Reset the OpenPGP app on the Ledger.
- moved all 3 of the sub-keys onto the card - successfully.

So: Now I have 3 sub-keys: 2 are curve 25519 and the encryption one is RSA4096. And I have an offline backup which includes the master certification key in addition to all 3 sub-keys.

I have no idea if the Ledger 2.0.0 firmware upgrade is part of the problem - it may just be a coincidence - but having a cv25519 encryption key certainly _used_ to be possible, before the upgrade.

**Comment by cedelavergne-ledger** [comment]
Hi,
The App has been refactored ands the backup mechanism reviewed.
The App is now in v2.1, still in `develop` branch.
