### ISSUE TITLE
"Historical Bytes" should not have a fixed length of 15 and be padded with trailing zeros

### ISSUE THREAD

**Issue by hko-s** [LedgerHQ/app-openpgp#74]
The card spec defines that historical bytes can have a length of up to 15 bytes. And it specifies that:

_"[..] The last 3 bytes of the Historical bytes are a status indicator byte and two processing status bytes SW1/SW2 (normally '9000')."_

This implementation returns the "historical bytes" field at a fixed length of 15 bytes, filled with trailing 0 bytes. As a result, it is unclear for consumers of that data, where the CTLV section ends, and which bytes to interpret as the status indicator byte and SW1/SW2.

I think that either 1) the historical bytes data should have a variable length, or 2) the padding zeros should be shifted, like this:

```
const unsigned char C_default_Histo[] = {0x00, 0x31,
                                         0xC5, // select method: by DF/partialDF; IO-file:readbinary; RFU???
                                         0x73,
                                         0xC0, // select method: by DF/partialDF ,
                                         0x01, // data coding style: ontime/byte
                                         0x80, // chaining
                                         0, 0, 0, 0, 0, // padding to total length of 15 bytes
                                         0x7F, // zero state (status indicator byte)
                                         0x90, 0x00};
```

In case 2, hard-coded access to the status indicator byte in the rest of the code base (such as access to `N_gpg_pstate->histo[7]`) would need to be adjusted.

I believe both approaches would be more in line with the intent of the card spec (and I believe that GnuPG's scdaemon would be able to process both variants).

Let me know if you'd like me to offer an MR for approach 2 (I think that's the easier and less error-prone thing to do, so I would propose to go with that)

**Comment by cedelavergne-ledger** [comment]
Fixed in v2.0.1
