### ISSUE TITLE
App is allowing operations even when ledger is locked?

### ISSUE THREAD

**Issue by dave7280** [LedgerHQ/app-openpgp#77]
Hi

I recently started using the app. It's great.
However i noticed one security issue that is concerning.

Once i open the app and let it idle for a while so ledger enters system wide PIN lock mode (willl request to reenter ledger pin again), the app is still running in background and allowing all kind of operations. 

The PGP app does not respect the fact that ledger is "locked" and the fact that ledger is demanding pin re-entry after system defined timeout period. You can perform all kind of operations once ledger enters timed-out PIN lock. The only protection against this is using UIF for now that requests you to confirm operation (and you won't be able to confirm unless you enter PIN).

Shouldn't the PGP app respect the fact that ledger is somehow "locked" ?
In BTC app it will not allow access to the keys and operations once ledger got locked.

Reproduction:
1. Set ledger system wide timeout for pin lock to 2 minutes
2. Open PGP app
3. Wait until ledger locks the screen and demands pin
4. You can still perform all operations with PGP app, even when the screen is locked.

Fix seems to be easy, just adding line of code that checks if ledger is in this pin-lock mode and refuse to do any kind of operations until it's unlocked.

**Comment by cedelavergne-ledger** [comment]
Hello,
App has been reforaced in v2.0.0. It is still in `develop` branch, not yet merged on `master`, neither deployed on Ledger Live.
I am not able to reproduce your issue: once the device is locked, I cannot send any command, and the _card_ is no more detected. I need first to unlock my device to be able to perform any operation, and then validate again my pin.
Please double check on your side...
