### ISSUE TITLE
keytocard silently fails for encryption subkey with cv25519

### ISSUE THREAD

**Issue by plup** [LedgerHQ/app-openpgp#78]
Hi guys !

I logged there a description of the problem I had today: https://superuser.com/questions/1724583/gpg-stub-for-encryption-subkey-not-working

Tell me if I can provide more information. I'll be using NIST curves instead for now.

**Comment by cedelavergne-ledger** [comment]
I had no problem to use `keytocard`.
During my tests, I have selected `Ed25519`, and verifying **Sign**/**Verify** (we still have a limitation with the **Decrypt** operation using `cv25519`).
