### ISSUE TITLE
RSA 3072/4096 generation broken on NanoX 2.2.1

### ISSUE THREAD

**Issue by jukefr** [LedgerHQ/app-openpgp#89]
Running latest version of the xl app (1.4.4) on NanoX latest fw 2.2.1 and generating an RSA keyset with either 3072 or 4096 crashes the app and reboots the ledger.
Only 2048 works.

**Comment by cedelavergne-ledger** [comment]
Hi,
RSA3072 is OK, in version v2.
For 4096, we still need to work on it. Please check https://github.com/LedgerHQ/app-openpgp/issues/83
